/**
 * Blog post loader — reads markdown files from content/blog/ directory.
 * Posts are generated by the marketing-bot's Website Content Agent.
 */

import fs from "fs"
import path from "path"

export interface BlogPost {
  slug: string
  title: string
  titleEs: string
  date: string
  /** Optional last-updated date (YYYY-MM-DD) from frontmatter; drives dateModified in schema. */
  updated: string
  author: string
  category: string
  tags: string[]
  description: string
  descriptionEs: string
  image: string
  readTime: string
  keywords: string[]
  contentEn: string
  contentEs: string
  file: string
}

const BLOG_DIR = path.join(process.cwd(), "content", "blog")

function parseFrontmatter(raw: string): { data: Record<string, string>; contentBody: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!match) return { data: {}, contentBody: raw }

  const data: Record<string, string> = {}
  const lines = match[1].split("\n")

  let currentKey = ""
  for (const line of lines) {
    // Skip schema sub-properties
    if (line.startsWith("  ")) continue

    const colonIdx = line.indexOf(":")
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim()
      let val = line.slice(colonIdx + 1).trim()
      // Strip surrounding quotes
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1)
      }
      data[key] = val
      currentKey = key
    }
  }

  return { data, contentBody: match[2] }
}

function parseArrayField(val: string): string[] {
  if (!val) return []
  // Handle [item1, item2] format
  const inner = val.replace(/^\[/, "").replace(/\]$/, "")
  if (!inner.trim()) return []
  return inner.split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean)
}

function markdownToHtml(md: string): string {
  let html = md

  // Headers
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>")
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>")

  // Bold and italic
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>")

  // Unordered lists
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>")
  html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>")

  // Ordered lists
  html = html.replace(/^\d+\. (.+)$/gm, "<li>$1</li>")

  // Links
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')

  // Paragraphs — wrap loose text lines
  const lines = html.split("\n")
  const result: string[] = []
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) {
      result.push("")
      continue
    }
    if (
      trimmed.startsWith("<h") ||
      trimmed.startsWith("<ul") ||
      trimmed.startsWith("<ol") ||
      trimmed.startsWith("<li") ||
      trimmed.startsWith("</")
    ) {
      result.push(trimmed)
    } else {
      result.push(`<p>${trimmed}</p>`)
    }
  }

  return result.join("\n")
}

export function getAllPosts(): BlogPost[] {
  if (!fs.existsSync(BLOG_DIR)) return []

  const files = fs.readdirSync(BLOG_DIR).filter((f) => f.endsWith(".md"))

  const posts: BlogPost[] = files
    .map((file) => {
      const raw = fs.readFileSync(path.join(BLOG_DIR, file), "utf-8")
      const { data, contentBody } = parseFrontmatter(raw)

      // Split EN/ES content
      const parts = contentBody.split("---SPANISH---")
      const contentEn = (parts[0] || "").trim()
      const contentEs = (parts[1] || "").trim()

      return {
        slug: data.slug || file.replace(/^\d{4}-\d{2}-\d{2}-/, "").replace(/\.md$/, ""),
        title: data.title || "",
        titleEs: data.titleEs || data.title || "",
        date: data.date || "",
        updated: data.updated || "",
        author: data.author || "Broke & Fixed Home Solutions",
        category: data.category || "tips",
        tags: parseArrayField(data.tags || ""),
        description: data.description || "",
        descriptionEs: data.descriptionEs || data.description || "",
        image: data.image || "",
        readTime: data.readTime || "5 min",
        keywords: parseArrayField(data.keywords || ""),
        contentEn,
        contentEs,
        file,
      }
    })
    .sort((a, b) => (b.date > a.date ? 1 : -1))

  return posts
}

export function getPostBySlug(slug: string): BlogPost | null {
  const posts = getAllPosts()
  return posts.find((p) => p.slug === slug) || null
}

export function getPostContent(post: BlogPost, locale: string): string {
  const raw = locale === "es" ? post.contentEs : post.contentEn
  return markdownToHtml(raw)
}

export function getPostTitle(post: BlogPost, locale: string): string {
  return locale === "es" ? post.titleEs : post.title
}

export function getPostDescription(post: BlogPost, locale: string): string {
  return locale === "es" ? post.descriptionEs : post.description
}

export interface FaqItem {
  question: string
  answer: string
}

// Strip inline markdown so schema text is clean plain text.
function stripInlineMarkdown(s: string): string {
  return s
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // [text](url) -> text
    .replace(/\*\*(.+?)\*\*/g, "$1") // bold
    .replace(/\*(.+?)\*/g, "$1") // italic
    .trim()
}

/**
 * Pull Q&A pairs out of a post's FAQ section for FAQPage JSON-LD.
 * Convention (see content/blog/*.md): a heading "## FAQ..." (EN) or
 * "## Preguntas Frecuentes..." (ES), then bold questions (**Question?**)
 * each followed by one or more answer paragraphs, until the next "## " heading.
 * Returns [] when no FAQ section is present so callers can skip the schema.
 */
export function extractFaqs(content: string): FaqItem[] {
  const lines = content.split("\n")
  let inFaq = false
  const faqLines: string[] = []
  for (const raw of lines) {
    const line = raw.trim()
    if (/^##\s+(FAQ|Frequently Asked|Preguntas Frecuentes)/i.test(line)) {
      inFaq = true
      continue
    }
    if (inFaq && /^##\s+/.test(line)) break // next section ends the FAQ block
    if (inFaq) faqLines.push(raw)
  }

  const faqs: FaqItem[] = []
  let currentQ: string | null = null
  let currentA: string[] = []
  const flush = () => {
    if (currentQ && currentA.length) {
      faqs.push({
        question: stripInlineMarkdown(currentQ),
        answer: stripInlineMarkdown(currentA.join(" ")),
      })
    }
    currentQ = null
    currentA = []
  }

  for (const raw of faqLines) {
    const line = raw.trim()
    // A question is a bold span at the start of the line. Two layouts exist
    // in our content: the bold question alone (answer in following paragraphs)
    // and the bold question with its answer inline on the same line.
    const qMatch = line.match(/^\*\*(.+?)\*\*\s*(.*)$/)
    if (qMatch) {
      flush()
      currentQ = qMatch[1]
      if (qMatch[2]) currentA.push(qMatch[2])
    } else if (currentQ && line) {
      currentA.push(line)
    }
  }
  flush()
  return faqs
}
