/**
 * Gallery data loader — reads project photos synced from marketing-bot.
 * Data is generated by scripts/sync_gallery.py in the marketing-bot repo.
 */

import galleryData from "./data/gallery-data.json"

export interface GalleryPhoto {
  filename: string
  phase: string
  note: string
  url: string
}

export interface GalleryProject {
  slug: string
  name: string
  service: string
  location: string
  photoCount: number
  phases: string[]
  photos: GalleryPhoto[]
  created: string
}

export function getAllProjects(): GalleryProject[] {
  return galleryData as GalleryProject[]
}

export function getProjectBySlug(slug: string): GalleryProject | null {
  return (galleryData as GalleryProject[]).find((p) => p.slug === slug) || null
}

export function getProjectsByService(service: string): GalleryProject[] {
  const lower = service.toLowerCase()
  return (galleryData as GalleryProject[]).filter(
    (p) => p.service.toLowerCase().includes(lower)
  )
}

export function getBeforeAfterPairs(project: GalleryProject): { before: GalleryPhoto; after: GalleryPhoto }[] {
  const befores = project.photos.filter((p) => p.phase === "before")
  const afters = project.photos.filter((p) => p.phase === "after")

  // Pair them up in order
  const pairs: { before: GalleryPhoto; after: GalleryPhoto }[] = []
  const count = Math.min(befores.length, afters.length)
  for (let i = 0; i < count; i++) {
    pairs.push({ before: befores[i], after: afters[i] })
  }
  return pairs
}
